version: 2

project_name: https2http

before:
  hooks:
    - go mod tidy

builds:
  - id: https2http
    main: .
    binary: https2http
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64

  - id: proxychecker
    main: ./cmd/proxychecker
    binary: proxychecker
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  disable: true

release:
  github:
    owner: LubyRuffy
    name: https2http
